name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create the data and the app dirs if they do not exist
            mkdir -p ~/data/capsule
            mkdir -p ${{ secrets.APP_PATH }}
            cd ${{ secrets.APP_PATH }}

            if [ ! -d ".git" ]; then
              git clone ${{ vars.REPO }} .
            else
              git pull
            fi

            # We use > for the first line to clear the file, and >> to append
            echo "DATABASE_URL=file:/app/data/prod.db" > .env
            echo "BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}" >> .env
            echo "BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}" >> .env
            echo "ALLOWED_USERS=${{ secrets.ALLOWED_USERS }}" >> .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

            docker compose up -d --build
            docker image prune -f
